#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2014 Miklos Szeredi.  All Rights Reserved.
#
# FS QA Test No. generic/035
#
# Check overwriting rename system call
#
seqfull=$0
. ./common/preamble
_begin_fstest auto quick

# Import common functions.


_require_test

# V1 minix has a 64MB max filesystem, too small for this test
[ "$FSTYP" = "minix" ] && [ "$MKFS_OPTIONS" = "-1" ] && _notrun "V1 minix 64MB filesystem fills up during test"
# Select appropriate golden output based on fstype
_link_out_file


rename_dir=$TEST_DIR/$$
mkdir -p $rename_dir

echo "overwriting regular file:"
file1=$rename_dir/file1
file2=$rename_dir/file2
touch $file1
touch $file2
$here/src/t_rename_overwrite $file1 $file2
rm $file2

echo "overwriting directory:"
dir1=$rename_dir/dir1
dir2=$rename_dir/dir2
mkdir $dir1
mkdir $dir2
$here/src/t_rename_overwrite $dir1 $dir2
rmdir $dir2

rmdir $rename_dir

# success, all done
status=0
exit
