#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2006 Silicon Graphics, Inc.  All Rights Reserved.
#
# FSQA Test No. 131
#
# lock test created from CXFSQA test lockfile_simple
#
. ./common/preamble
_begin_fstest perms auto quick

# Import common functions.
. ./common/filter
. ./common/locktest

_require_test
_require_test_fcntl_advisory_locks

# V1 minix has a 64MB max filesystem, too small for this test
[ "$FSTYP" = "minix" ] && [ "$MKFS_OPTIONS" = "-1" ] && _notrun "V1 minix filesystem too small for network test setup"
_run_locktest

exit
