#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2011 Gražvydas Ignotas
#
#
# Check that no duplicate d_off values are returned and that those
# values are seekable. Most work is done by the C program here.
#
. ./common/preamble
_begin_fstest dir auto quick

# Override the default cleanup function.
_cleanup()
{
	rm -rf $TEST_DIR/ttt
}

# Import common functions.
. ./common/filter

_require_test

# V1 minix has a 64MB max filesystem, too small for this test
[ "$FSTYP" = "minix" ] && [ "$MKFS_OPTIONS" = "-1" ] && _notrun "V1 minix 64MB filesystem fills up during directory operations test"
mkdir $TEST_DIR/ttt
for n in {1..168}; do
    touch $TEST_DIR/ttt/$n;
done
$here/src/t_dir_offset2 $TEST_DIR/ttt

# success, all done
echo "*** done"
status=0
