#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2013 Red Hat, Inc.  All Rights Reserved.
#
# FS QA Test No. 313
#
# Check ctime and mtime are updated on truncate(2) and ftruncate(2)
#
# Regression test for commit:
# 3972f26 btrfs: update timestamps on truncate()
#
. ./common/preamble
_begin_fstest auto quick

# Override the default cleanup function.
_cleanup()
{
    cd /
    rm -f $testfile
}

# Import common functions.
. ./common/filter

_require_test

# V1 minix has a 64MB max filesystem, too small for this test
[ "$FSTYP" = "minix" ] && [ "$MKFS_OPTIONS" = "-1" ] && _notrun "V1 minix 64MB filesystem fills up during write test"
testfile=$TEST_DIR/testfile.$seq

echo "Silence is golden"

$here/src/t_truncate_cmtime $testfile 2>&1

status=0
exit
